import { AssignedJob, Interview, PersonalTask } from "./types";

// Dummy data for Today Tasks page
// TODO: Replace with real API calls when backend is ready

export const dummyAssignedJobs: AssignedJob[] = [
  {
    id: "1",
    jobTitle: "Senior Software Engineer",
    clientName: "TechCorp Solutions",
    location: "San Francisco, CA",
    priority: "high",
    deadline: "2024-01-15",
    aemsDeadline: "2024-01-12",
    candidatesCount: 8,
    status: "In Progress",
    recruiter: "John Smith"
  },
  {
    id: "2", 
    jobTitle: "Product Manager",
    clientName: "InnovateLabs",
    location: "New York, NY",
    priority: "medium",
    deadline: "2024-01-20",
    aemsDeadline: "2024-01-17",
    candidatesCount: 5,
    status: "To-do",
    recruiter: "Sarah Johnson"
  },
  {
    id: "3",
    jobTitle: "UX Designer",
    clientName: "DesignStudio Pro",
    location: "Austin, TX",
    priority: "low",
    deadline: "2024-01-25",
    aemsDeadline: "2024-01-22",
    candidatesCount: 12,
    status: "To-do",
    recruiter: "Mike Chen"
  },
  {
    id: "4",
    jobTitle: "Data Scientist",
    clientName: "Analytics Inc",
    location: "Seattle, WA",
    priority: "high",
    deadline: "2024-01-18",
    aemsDeadline: "2024-01-15",
    candidatesCount: 6,
    status: "In Progress",
    recruiter: "Emily Davis"
  },
  {
    id: "5",
    jobTitle: "DevOps Engineer",
    clientName: "CloudTech Systems",
    location: "Denver, CO",
    priority: "medium",
    deadline: "2024-01-22",
    aemsDeadline: "2024-01-19",
    candidatesCount: 9,
    status: "In Progress",
    recruiter: "Alex Rodriguez"
  },
  {
    id: "6",
    jobTitle: "Marketing Manager",
    clientName: "GrowthCorp",
    location: "Chicago, IL",
    priority: "low",
    deadline: "2024-01-28",
    aemsDeadline: "2024-01-25",
    candidatesCount: 4,
    status: "To-do",
    recruiter: "Lisa Wang"
  },
  {
    id: "7",
    jobTitle: "Full Stack Developer",
    clientName: "StartupXYZ",
    location: "Boston, MA",
    priority: "high",
    deadline: "2024-01-16",
    aemsDeadline: "2024-01-13",
    candidatesCount: 11,
    status: "In Progress",
    recruiter: "David Kim"
  },
  {
    id: "8",
    jobTitle: "Sales Director",
    clientName: "Enterprise Solutions",
    location: "Miami, FL",
    priority: "medium",
    deadline: "2024-01-24",
    aemsDeadline: "2024-01-21",
    candidatesCount: 7,
    status: "Completed",
    recruiter: "Maria Garcia"
  },
  {
    id: "9",
    jobTitle: "Frontend Developer",
    clientName: "WebCraft Studios",
    location: "Portland, OR",
    priority: "high",
    deadline: "2024-01-19",
    aemsDeadline: "2024-01-16",
    candidatesCount: 15,
    status: "In Progress",
    recruiter: "Tom Wilson"
  },
  {
    id: "10",
    jobTitle: "Backend Developer",
    clientName: "DataFlow Inc",
    location: "Phoenix, AZ",
    priority: "medium",
    deadline: "2024-01-26",
    aemsDeadline: "2024-01-23",
    candidatesCount: 9,
    status: "In Progress",
    recruiter: "Jennifer Lee"
  },
  {
    id: "11",
    jobTitle: "Mobile App Developer",
    clientName: "AppTech Solutions",
    location: "Nashville, TN",
    priority: "high",
    deadline: "2024-01-17",
    aemsDeadline: "2024-01-14",
    candidatesCount: 6,
    status: "To-do",
    recruiter: "Robert Brown"
  },
  {
    id: "12",
    jobTitle: "Cloud Architect",
    clientName: "SkyTech Systems",
    location: "Salt Lake City, UT",
    priority: "medium",
    deadline: "2024-01-30",
    aemsDeadline: "2024-01-27",
    candidatesCount: 4,
    status: "In Progress",
    recruiter: "Amanda Taylor"
  },
  {
    id: "13",
    jobTitle: "Cybersecurity Specialist",
    clientName: "SecureNet Corp",
    location: "Raleigh, NC",
    priority: "high",
    deadline: "2024-01-21",
    aemsDeadline: "2024-01-18",
    candidatesCount: 8,
    status: "In Progress",
    recruiter: "Kevin Martinez"
  },
  {
    id: "14",
    jobTitle: "AI/ML Engineer",
    clientName: "IntelliTech Labs",
    location: "Minneapolis, MN",
    priority: "high",
    deadline: "2024-01-23",
    aemsDeadline: "2024-01-20",
    candidatesCount: 12,
    status: "In Progress",
    recruiter: "Rachel Green"
  },
  {
    id: "15",
    jobTitle: "QA Engineer",
    clientName: "QualityFirst Inc",
    location: "Kansas City, MO",
    priority: "medium",
    deadline: "2024-01-27",
    aemsDeadline: "2024-01-24",
    candidatesCount: 7,
    status: "Completed",
    recruiter: "James White"
  },
  {
    id: "16",
    jobTitle: "Business Analyst",
    clientName: "StrategyCorp",
    location: "Tampa, FL",
    priority: "low",
    deadline: "2024-02-01",
    aemsDeadline: "2024-01-29",
    candidatesCount: 5,
    status: "To-do",
    recruiter: "Michelle Adams"
  },
  {
    id: "17",
    jobTitle: "Technical Writer",
    clientName: "DocuTech Solutions",
    location: "San Diego, CA",
    priority: "low",
    deadline: "2024-02-05",
    aemsDeadline: "2024-02-02",
    candidatesCount: 3,
    status: "In Progress",
    recruiter: "Daniel Clark"
  },
  {
    id: "18",
    jobTitle: "Project Manager",
    clientName: "ProjFlow Systems",
    location: "Orlando, FL",
    priority: "medium",
    deadline: "2024-01-29",
    aemsDeadline: "2024-01-26",
    candidatesCount: 10,
    status: "In Progress",
    recruiter: "Stephanie Hall"
  },
  {
    id: "19",
    jobTitle: "Database Administrator",
    clientName: "DataVault Corp",
    location: "Las Vegas, NV",
    priority: "high",
    deadline: "2024-01-25",
    aemsDeadline: "2024-01-22",
    candidatesCount: 6,
    status: "In Progress",
    recruiter: "Christopher Young"
  },
  {
    id: "20",
    jobTitle: "Network Engineer",
    clientName: "ConnectTech Inc",
    location: "Columbus, OH",
    priority: "medium",
    deadline: "2024-02-03",
    aemsDeadline: "2024-01-31",
    candidatesCount: 8,
    status: "To-do",
    recruiter: "Nicole King"
  }
];

export const dummyInterviews: Interview[] = [
  {
    id: "1",
    candidateName: "Alice Johnson",
    candidateEmail: "alice.johnson@email.com",
    candidatePhone: "+1 (555) 123-4567",
    jobTitle: "Senior Software Engineer",
    clientName: "TechCorp Solutions",
    interviewType: "video",
    scheduledTime: new Date().toISOString().split('T')[0] + "T10:00:00",
    duration: 60,
    status: "scheduled",
    meetingLink: "https://meet.zoom.us/j/123456789",
    notes: "Technical interview focusing on React and Node.js"
  },
  {
    id: "2",
    candidateName: "Bob Smith",
    candidateEmail: "bob.smith@email.com", 
    candidatePhone: "+1 (555) 987-6543",
    jobTitle: "Product Manager",
    clientName: "InnovateLabs",
    interviewType: "phone",
    scheduledTime: new Date().toISOString().split('T')[0] + "T14:30:00",
    duration: 45,
    status: "scheduled",
    notes: "Initial screening call"
  },
  {
    id: "3",
    candidateName: "Carol Davis",
    candidateEmail: "carol.davis@email.com",
    candidatePhone: "+1 (555) 456-7890",
    jobTitle: "UX Designer", 
    clientName: "DesignStudio Pro",
    interviewType: "in-person",
    scheduledTime: new Date().toISOString().split('T')[0] + "T16:00:00",
    duration: 90,
    status: "scheduled",
    location: "DesignStudio Pro Office, Austin TX",
    notes: "Portfolio review and design challenge"
  },
  {
    id: "4",
    candidateName: "David Wilson",
    candidateEmail: "david.wilson@email.com",
    candidatePhone: "+1 (555) 234-5678",
    jobTitle: "Data Scientist",
    clientName: "Analytics Inc",
    interviewType: "video",
    scheduledTime: new Date().toISOString().split('T')[0] + "T09:00:00",
    duration: 75,
    status: "completed",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    notes: "Machine learning algorithms and statistical analysis discussion"
  },
  {
    id: "5",
    candidateName: "Emma Brown",
    candidateEmail: "emma.brown@email.com",
    candidatePhone: "+1 (555) 345-6789",
    jobTitle: "DevOps Engineer",
    clientName: "CloudTech Systems",
    interviewType: "phone",
    scheduledTime: new Date().toISOString().split('T')[0] + "T11:30:00",
    duration: 50,
    status: "scheduled",
    notes: "Infrastructure and deployment strategies discussion"
  },
  {
    id: "6",
    candidateName: "Frank Miller",
    candidateEmail: "frank.miller@email.com",
    candidatePhone: "+1 (555) 456-7890",
    jobTitle: "Full Stack Developer",
    clientName: "StartupXYZ",
    interviewType: "in-person",
    scheduledTime: new Date().toISOString().split('T')[0] + "T15:30:00",
    duration: 90,
    status: "rescheduled",
    location: "StartupXYZ Office, Boston MA",
    notes: "Coding challenge and system design discussion"
  },
  {
    id: "7",
    candidateName: "Grace Lee",
    candidateEmail: "grace.lee@email.com",
    candidatePhone: "+1 (555) 567-8901",
    jobTitle: "Frontend Developer",
    clientName: "WebCraft Studios",
    interviewType: "video",
    scheduledTime: new Date().toISOString().split('T')[0] + "T13:00:00",
    duration: 60,
    status: "scheduled",
    meetingLink: "https://teams.microsoft.com/l/meetup-join/xyz",
    notes: "React and TypeScript technical assessment"
  },
  {
    id: "8",
    candidateName: "Henry Chen",
    candidateEmail: "henry.chen@email.com",
    candidatePhone: "+1 (555) 678-9012",
    jobTitle: "Backend Developer",
    clientName: "DataFlow Inc",
    interviewType: "phone",
    scheduledTime: new Date().toISOString().split('T')[0] + "T17:00:00",
    duration: 45,
    status: "cancelled",
    notes: "Candidate cancelled due to personal emergency"
  }
];

export const dummyUpcomingInterviews: Interview[] = [
  {
    id: "upcoming-1",
    candidateName: "Michael Rodriguez",
    candidateEmail: "michael.rodriguez@email.com",
    candidatePhone: "+1 (555) 111-2222",
    jobTitle: "Senior Software Engineer",
    clientName: "TechCorp Solutions",
    interviewType: "video",
    scheduledTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T10:00:00",
    duration: 60,
    status: "scheduled",
    meetingLink: "https://meet.zoom.us/j/111111111",
    notes: "Technical interview - React and Node.js focus"
  },
  {
    id: "upcoming-2",
    candidateName: "Sarah Thompson",
    candidateEmail: "sarah.thompson@email.com",
    candidatePhone: "+1 (555) 333-4444",
    jobTitle: "Product Manager",
    clientName: "InnovateLabs",
    interviewType: "phone",
    scheduledTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T14:30:00",
    duration: 45,
    status: "scheduled",
    notes: "Initial screening call"
  },
  {
    id: "upcoming-3",
    candidateName: "James Wilson",
    candidateEmail: "james.wilson@email.com",
    candidatePhone: "+1 (555) 555-6666",
    jobTitle: "UX Designer",
    clientName: "DesignStudio Pro",
    interviewType: "in-person",
    scheduledTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T16:00:00",
    duration: 90,
    status: "scheduled",
    location: "DesignStudio Pro Office, Austin TX",
    notes: "Portfolio review and design challenge"
  },
  {
    id: "upcoming-4",
    candidateName: "Lisa Chen",
    candidateEmail: "lisa.chen@email.com",
    candidatePhone: "+1 (555) 777-8888",
    jobTitle: "Data Scientist",
    clientName: "Analytics Inc",
    interviewType: "video",
    scheduledTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T09:00:00",
    duration: 75,
    status: "scheduled",
    meetingLink: "https://meet.google.com/lmn-opqr-stu",
    notes: "Machine learning algorithms discussion"
  },
  {
    id: "upcoming-5",
    candidateName: "Robert Davis",
    candidateEmail: "robert.davis@email.com",
    candidatePhone: "+1 (555) 999-0000",
    jobTitle: "DevOps Engineer",
    clientName: "CloudTech Systems",
    interviewType: "phone",
    scheduledTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T11:30:00",
    duration: 50,
    status: "scheduled",
    notes: "Infrastructure and deployment strategies"
  },
  {
    id: "upcoming-6",
    candidateName: "Jennifer Martinez",
    candidateEmail: "jennifer.martinez@email.com",
    candidatePhone: "+1 (555) 123-4567",
    jobTitle: "Full Stack Developer",
    clientName: "StartupXYZ",
    interviewType: "in-person",
    scheduledTime: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T15:30:00",
    duration: 90,
    status: "scheduled",
    location: "StartupXYZ Office, Boston MA",
    notes: "Coding challenge and system design"
  },
  {
    id: "upcoming-7",
    candidateName: "Kevin Anderson",
    candidateEmail: "kevin.anderson@email.com",
    candidatePhone: "+1 (555) 234-5678",
    jobTitle: "Frontend Developer",
    clientName: "WebCraft Studios",
    interviewType: "video",
    scheduledTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T13:00:00",
    duration: 60,
    status: "scheduled",
    meetingLink: "https://teams.microsoft.com/l/meetup-join/abc",
    notes: "React and TypeScript assessment"
  },
  {
    id: "upcoming-8",
    candidateName: "Amanda Taylor",
    candidateEmail: "amanda.taylor@email.com",
    candidatePhone: "+1 (555) 345-6789",
    jobTitle: "Backend Developer",
    clientName: "DataFlow Inc",
    interviewType: "phone",
    scheduledTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T17:00:00",
    duration: 45,
    status: "scheduled",
    notes: "API design and database optimization"
  },
  {
    id: "upcoming-9",
    candidateName: "Daniel Kim",
    candidateEmail: "daniel.kim@email.com",
    candidatePhone: "+1 (555) 456-7890",
    jobTitle: "Mobile App Developer",
    clientName: "AppTech Solutions",
    interviewType: "video",
    scheduledTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T10:30:00",
    duration: 60,
    status: "scheduled",
    meetingLink: "https://meet.zoom.us/j/222222222",
    notes: "iOS and Android development experience"
  },
  {
    id: "upcoming-10",
    candidateName: "Rachel Green",
    candidateEmail: "rachel.green@email.com",
    candidatePhone: "+1 (555) 567-8901",
    jobTitle: "Cloud Architect",
    clientName: "SkyTech Systems",
    interviewType: "in-person",
    scheduledTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + "T14:00:00",
    duration: 90,
    status: "scheduled",
    location: "SkyTech Systems Office, Salt Lake City UT",
    notes: "AWS and Azure architecture discussion"
  }
];

export const dummyPersonalTasks: PersonalTask[] = [
  {
    id: "1",
    title: "Check CV status for John Smith",
    description: "Follow up on CV submission for Senior Developer position at TechCorp",
    priority: "high",
    dueDate: "2024-01-10",
    dueTime: "10:00",
    status: "to-do",
    category: "follow-up",
    followUpType: "cv-received",
    followUpStatus: "pending",
    relatedCandidate: "John Smith",
    relatedJob: "Senior Developer",
    relatedClient: "TechCorp",
    createdAt: "2024-01-09"
  },
  {
    id: "2",
    title: "Update job descriptions",
    description: "Review and update 5 job descriptions based on client feedback",
    priority: "high",
    dueDate: "2024-01-10",
    dueTime: "12:00",
    status: "inprogress",
    category: "admin",
    createdAt: "2024-01-08"
  },
  {
    id: "3",
    title: "Follow up on candidate response",
    description: "Check if Sarah Johnson has responded to our interview invitation",
    priority: "medium",
    dueDate: "2024-01-10",
    dueTime: "14:00",
    status: "to-do",
    category: "follow-up",
    followUpType: "candidate-response",
    followUpStatus: "pending",
    relatedCandidate: "Sarah Johnson",
    relatedJob: "Product Manager",
    relatedClient: "InnovateLabs",
    createdAt: "2024-01-09"
  },
  {
    id: "4",
    title: "Research new sourcing channels",
    description: "Explore LinkedIn Recruiter alternatives and new job boards",
    priority: "low",
    dueDate: "2024-01-12",
    status: "to-do",
    category: "research",
    createdAt: "2024-01-07"
  }
];
